# _config.yml
title: Ege Okumus - Bioinformatics Portfolio
baseurl: ""
# Sass/SCSS configuration
sass:
  sass_dir: _sass          # Default location for SCSS files, though assets/css works too
  style: compressed        # Compresses the CSS for production, or use 'expanded' for debugging
                           # Note: If your style.scss is directly in assets/css/, this might not be strictly needed,
                           # but it's good practice. Jekyll usually detects assets/css/style.scss automatically.

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Ensure show_downloads is false if it was from cayman theme
show_downloads: false
